// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.26.1

import { Writer, Reader } from "as-proto/assembly";

export class RuneId {
  static encode(message: RuneId, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.block);

    writer.uint32(18);
    writer.string(message.tx);
  }

  static decode(reader: Reader, length: i32): RuneId {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new RuneId();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.block = reader.string();
          break;

        case 2:
          message.tx = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  block: string;
  tx: string;

  constructor(block: string = "", tx: string = "") {
    this.block = block;
    this.tx = tx;
  }
}
