// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.26.1

import { Writer, Reader } from "as-proto/assembly";

export class Terms {
  static encode(message: Terms, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.cap);

    writer.uint32(18);
    writer.string(message.amount);
  }

  static decode(reader: Reader, length: i32): Terms {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Terms();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.cap = reader.string();
          break;

        case 2:
          message.amount = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  cap: string;
  amount: string;

  constructor(cap: string = "", amount: string = "") {
    this.cap = cap;
    this.amount = amount;
  }
}
