// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.26.1

import { Writer, Reader } from "as-proto/assembly";
import { RunestoneBuf } from "./RunestoneBuf";

export class RunestoneBufs {
  static encode(message: RunestoneBufs, writer: Writer): void {
    const runestoneBufs = message.runestoneBufs;
    for (let i: i32 = 0; i < runestoneBufs.length; ++i) {
      writer.uint32(10);
      writer.fork();
      RunestoneBuf.encode(runestoneBufs[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): RunestoneBufs {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new RunestoneBufs();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.runestoneBufs.push(
            RunestoneBuf.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  runestoneBufs: Array<RunestoneBuf>;

  constructor(runestoneBufs: Array<RunestoneBuf> = []) {
    this.runestoneBufs = runestoneBufs;
  }
}
