// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.26.1

import { Writer, Reader } from "as-proto/assembly";

export class Rune {
  static encode(message: Rune, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.name);

    writer.uint32(18);
    writer.string(message.symbol);
  }

  static decode(reader: Reader, length: i32): Rune {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Rune();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.name = reader.string();
          break;

        case 2:
          message.symbol = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  name: string;
  symbol: string;

  constructor(name: string = "", symbol: string = "") {
    this.name = name;
    this.symbol = symbol;
  }
}
